apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hxx8
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0060-tenant/tkrw-pr712-0075-0060-app/devfile-sample-hxx8@sha256:b7183c6f7f0038e09e1e12a65880510def7a6a64ca34b5b242e1bc0600f279a5
        name: my-nodejs
        resources: {}
status: {}
